import { PrinterBrand, FilamentType, FilamentProfile } from './types';

export const PRINTER_BRANDS: PrinterBrand[] = [
  'Bambu Lab', 'Anycubic', 'Creality', 'Prusa', 'Ultimaker', 'Elegoo', 'Other'
];

export const FILAMENT_MANUFACTURERS: string[] = [
  'Atomic Filament', 'Bambu Lab', 'BASF Ultrafuse', 'ColorFabb', 'Creality', 'DSM Novamid', 'eSUN', 'Extrudr', 'Fiberlogy', 'Fillamentum', 'FormFutura', 'Geeetech', 'Hatchbox', 'IGUS', 'Kimya (Armor)', 'MatterHackers', 'NinjaTek', 'Overture', 'Polymaker', 'Priline', 'Proto-pasta', 'Prusa', 'Sakata', 'Spectrum', 'Sunlu', 'Taulman3D', 'XSTRAND (OwensCorning)', 'Other'
].sort();


export const FILAMENT_TYPES: FilamentType[] = [
  'PLA', 'ABS', 'PETG', 'TPU', 'ASA', 'PC', 'PA-CF', 'PA-GF', 'Copolyester', 'PETT', 'Nylon', 'TPE', 'Other'
];

const GENERIC_NOTE = "Default print speed and retraction are generic; please tune for your printer.";

export const PRESET_PROFILES: FilamentProfile[] = [
  { id: 'preset-1', profileName: 'Bambu Lab PLA Basic', printerBrand: 'Bambu Lab', manufacturer: 'Bambu Lab', brand: 'PLA Basic', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 210, bedTemp: 40, printSpeed: 150, retractionDistance: 0.8, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-2', profileName: 'Bambu Lab PLA Tough', printerBrand: 'Bambu Lab', manufacturer: 'Bambu Lab', brand: 'PLA Tough', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 215, bedTemp: 55, printSpeed: 150, retractionDistance: 0.8, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.25, notes: GENERIC_NOTE },
  { id: 'preset-3', profileName: 'Bambu Lab PETG', printerBrand: 'Bambu Lab', manufacturer: 'Bambu Lab', brand: 'PETG Basic', filamentType: 'PETG', filamentDiameter: 1.75, nozzleTemp: 235, bedTemp: 70, printSpeed: 100, retractionDistance: 0.8, retractionSpeed: 30, fanSpeed: 50, spoolWeight: 1000, density: 1.27, dryingTemp: 65, dryingTime: '8h', notes: GENERIC_NOTE },
  { id: 'preset-4', profileName: 'Bambu Lab ABS', printerBrand: 'Bambu Lab', manufacturer: 'Bambu Lab', brand: 'ABS', filamentType: 'ABS', filamentDiameter: 1.75, nozzleTemp: 260, bedTemp: 100, printSpeed: 120, retractionDistance: 0.8, retractionSpeed: 30, fanSpeed: 0, spoolWeight: 1000, density: 1.04, notes: GENERIC_NOTE },
  { id: 'preset-5', profileName: 'Bambu Lab TPU (Flex 95A)', printerBrand: 'Bambu Lab', manufacturer: 'Bambu Lab', brand: 'TPU 95A', filamentType: 'TPU', filamentDiameter: 1.75, nozzleTemp: 225, bedTemp: 45, printSpeed: 40, retractionDistance: 1, retractionSpeed: 25, fanSpeed: 15, spoolWeight: 1000, density: 1.21, dryingTemp: 70, dryingTime: '12h', notes: GENERIC_NOTE },
  { id: 'preset-6', profileName: 'Prusament PLA', printerBrand: 'Prusa', manufacturer: 'Prusa', brand: 'Prusament', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 215, bedTemp: 60, printSpeed: 80, retractionDistance: 0.8, retractionSpeed: 35, fanSpeed: 100, spoolWeight: 1000, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-7', profileName: 'Prusament PETG', printerBrand: 'Prusa', manufacturer: 'Prusa', brand: 'Prusament', filamentType: 'PETG', filamentDiameter: 1.75, nozzleTemp: 245, bedTemp: 85, printSpeed: 60, retractionDistance: 1, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.27, dryingTemp: 65, dryingTime: '4h', notes: GENERIC_NOTE },
  { id: 'preset-8', profileName: 'Prusament ASA', printerBrand: 'Prusa', manufacturer: 'Prusa', brand: 'Prusament', filamentType: 'ASA', filamentDiameter: 1.75, nozzleTemp: 258, bedTemp: 100, printSpeed: 60, retractionDistance: 1, retractionSpeed: 35, fanSpeed: 0, spoolWeight: 1000, density: 1.07, dryingTemp: 80, dryingTime: '4h', notes: GENERIC_NOTE },
  { id: 'preset-9', profileName: 'eSUN PLA+', printerBrand: 'Other', manufacturer: 'eSUN', brand: 'PLA+', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 215, bedTemp: 55, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-10', profileName: 'eSUN PETG', printerBrand: 'Other', manufacturer: 'eSUN', brand: 'PETG', filamentType: 'PETG', filamentDiameter: 1.75, nozzleTemp: 240, bedTemp: 75, printSpeed: 50, retractionDistance: 2, retractionSpeed: 40, fanSpeed: 50, spoolWeight: 1000, density: 1.27, dryingTemp: 65, dryingTime: '6h', notes: GENERIC_NOTE },
  { id: 'preset-11', profileName: 'eSUN ABS+', printerBrand: 'Other', manufacturer: 'eSUN', brand: 'ABS+', filamentType: 'ABS', filamentDiameter: 1.75, nozzleTemp: 250, bedTemp: 95, printSpeed: 60, retractionDistance: 2, retractionSpeed: 40, fanSpeed: 0, spoolWeight: 1000, density: 1.05, notes: GENERIC_NOTE },
  { id: 'preset-12', profileName: 'eSUN TPU-95A', printerBrand: 'Other', manufacturer: 'eSUN', brand: 'eFlex', filamentType: 'TPU', filamentDiameter: 1.75, nozzleTemp: 230, bedTemp: 50, printSpeed: 30, retractionDistance: 1, retractionSpeed: 25, fanSpeed: 10, spoolWeight: 1000, density: 1.2, dryingTemp: 50, dryingTime: '6h', notes: GENERIC_NOTE },
  { id: 'preset-13', profileName: 'Sunlu PLA', printerBrand: 'Other', manufacturer: 'Sunlu', brand: 'PLA', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 205, bedTemp: 55, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-14', profileName: 'Sunlu PETG', printerBrand: 'Other', manufacturer: 'Sunlu', brand: 'PETG', filamentType: 'PETG', filamentDiameter: 1.75, nozzleTemp: 240, bedTemp: 70, printSpeed: 50, retractionDistance: 2, retractionSpeed: 40, fanSpeed: 50, spoolWeight: 1000, density: 1.27, dryingTemp: 65, dryingTime: '4h', notes: GENERIC_NOTE },
  { id: 'preset-15', profileName: 'Sunlu TPU', printerBrand: 'Other', manufacturer: 'Sunlu', brand: 'TPU', filamentType: 'TPU', filamentDiameter: 1.75, nozzleTemp: 220, bedTemp: 50, printSpeed: 30, retractionDistance: 1, retractionSpeed: 25, fanSpeed: 15, spoolWeight: 1000, density: 1.2, dryingTemp: 50, dryingTime: '6h', notes: GENERIC_NOTE },
  { id: 'preset-16', profileName: 'Polymaker PolyLite PLA', printerBrand: 'Other', manufacturer: 'Polymaker', brand: 'PolyLite', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 200, bedTemp: 55, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.23, notes: GENERIC_NOTE },
  { id: 'preset-17', profileName: 'Polymaker PolyTerra PLA', printerBrand: 'Other', manufacturer: 'Polymaker', brand: 'PolyTerra', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 200, bedTemp: 55, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.22, notes: GENERIC_NOTE },
  { id: 'preset-18', profileName: 'Polymaker PolyMax PLA', printerBrand: 'Other', manufacturer: 'Polymaker', brand: 'PolyMax', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 220, bedTemp: 60, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.25, notes: GENERIC_NOTE },
  { id: 'preset-19', profileName: 'Polymaker PolyLite PETG', printerBrand: 'Other', manufacturer: 'Polymaker', brand: 'PolyLite', filamentType: 'PETG', filamentDiameter: 1.75, nozzleTemp: 240, bedTemp: 73, printSpeed: 50, retractionDistance: 2, retractionSpeed: 40, fanSpeed: 50, spoolWeight: 1000, density: 1.23, dryingTemp: 70, dryingTime: '8h', notes: GENERIC_NOTE },
  { id: 'preset-20', profileName: 'Polymaker PolyMax PC', printerBrand: 'Other', manufacturer: 'Polymaker', brand: 'PolyMax', filamentType: 'PC', filamentDiameter: 1.75, nozzleTemp: 260, bedTemp: 95, printSpeed: 40, retractionDistance: 1.5, retractionSpeed: 35, fanSpeed: 0, spoolWeight: 1000, density: 1.2, dryingTemp: 100, dryingTime: '12h', notes: GENERIC_NOTE },
  { id: 'preset-21', profileName: 'Polymaker PolyMide PA6-CF', printerBrand: 'Other', manufacturer: 'Polymaker', brand: 'PolyMide', filamentType: 'PA-CF', filamentDiameter: 1.75, nozzleTemp: 290, bedTemp: 90, printSpeed: 40, retractionDistance: 1, retractionSpeed: 30, fanSpeed: 0, spoolWeight: 500, density: 1.24, dryingTemp: 80, dryingTime: '12h', notes: "Hardened nozzle recommended. " + GENERIC_NOTE },
  { id: 'preset-22', profileName: 'ColorFabb PLA/PHA', printerBrand: 'Other', manufacturer: 'ColorFabb', brand: 'PLA/PHA', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 208, bedTemp: 50, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 750, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-23', profileName: 'ColorFabb XT (PETG)', printerBrand: 'Other', manufacturer: 'ColorFabb', brand: 'ColorFabb XT', filamentType: 'Copolyester', filamentDiameter: 1.75, nozzleTemp: 250, bedTemp: 75, printSpeed: 50, retractionDistance: 2, retractionSpeed: 40, fanSpeed: 15, spoolWeight: 750, density: 1.27, dryingTemp: 65, dryingTime: '4h', notes: GENERIC_NOTE },
  { id: 'preset-24', profileName: 'Fillamentum Crystal Clear PLA', printerBrand: 'Other', manufacturer: 'Fillamentum', brand: 'Crystal Clear', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 210, bedTemp: 60, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 750, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-25', profileName: 'Fillamentum ASA', printerBrand: 'Other', manufacturer: 'Fillamentum', brand: 'ASA Extrafill', filamentType: 'ASA', filamentDiameter: 1.75, nozzleTemp: 260, bedTemp: 95, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 35, fanSpeed: 0, spoolWeight: 750, density: 1.07, dryingTemp: 80, dryingTime: '4h', notes: GENERIC_NOTE },
  { id: 'preset-26', profileName: 'BASF Ultrafuse PET CF', printerBrand: 'Other', manufacturer: 'BASF Ultrafuse', brand: 'Ultrafuse PET CF15', filamentType: 'PA-CF', filamentDiameter: 1.75, nozzleTemp: 260, bedTemp: 80, printSpeed: 50, retractionDistance: 1, retractionSpeed: 30, fanSpeed: 0, spoolWeight: 750, density: 1.4, dryingTemp: 70, dryingTime: '6h', notes: "Hardened nozzle recommended. " + GENERIC_NOTE },
  { id: 'preset-27', profileName: 'Taulman3D Bridge Nylon', printerBrand: 'Other', manufacturer: 'Taulman3D', brand: 'Bridge Nylon', filamentType: 'Nylon', filamentDiameter: 1.75, nozzleTemp: 245, bedTemp: 75, printSpeed: 40, retractionDistance: 1.5, retractionSpeed: 35, fanSpeed: 0, spoolWeight: 450, density: 1.14, dryingTemp: 80, dryingTime: '8h', notes: GENERIC_NOTE },
  { id: 'preset-28', profileName: 'MatterHackers NylonX', printerBrand: 'Other', manufacturer: 'MatterHackers', brand: 'NylonX', filamentType: 'PA-CF', filamentDiameter: 1.75, nozzleTemp: 250, bedTemp: 60, printSpeed: 50, retractionDistance: 1, retractionSpeed: 30, fanSpeed: 0, spoolWeight: 500, density: 1.15, dryingTemp: 90, dryingTime: '12h', notes: "Hardened nozzle recommended. " + GENERIC_NOTE },
  { id: 'preset-29', profileName: 'Hatchbox PLA', printerBrand: 'Other', manufacturer: 'Hatchbox', brand: 'PLA', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 195, bedTemp: 55, printSpeed: 60, retractionDistance: 1.5, retractionSpeed: 40, fanSpeed: 100, spoolWeight: 1000, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-30', profileName: 'Overture PETG', printerBrand: 'Other', manufacturer: 'Overture', brand: 'PETG', filamentType: 'PETG', filamentDiameter: 1.75, nozzleTemp: 240, bedTemp: 70, printSpeed: 50, retractionDistance: 2, retractionSpeed: 40, fanSpeed: 50, spoolWeight: 1000, density: 1.27, dryingTemp: 65, dryingTime: '6h', notes: GENERIC_NOTE },
  { id: 'preset-31', profileName: 'Creality PLA', printerBrand: 'Creality', manufacturer: 'Creality', brand: 'Ender PLA', filamentType: 'PLA', filamentDiameter: 1.75, nozzleTemp: 200, bedTemp: 50, printSpeed: 60, retractionDistance: 5, retractionSpeed: 45, fanSpeed: 100, spoolWeight: 1000, density: 1.24, notes: GENERIC_NOTE },
  { id: 'preset-32', profileName: 'NinjaTek NinjaFlex (TPU 85A)', printerBrand: 'Other', manufacturer: 'NinjaTek', brand: 'NinjaFlex', filamentType: 'TPU', filamentDiameter: 1.75, nozzleTemp: 225, bedTemp: 40, printSpeed: 20, retractionDistance: 1, retractionSpeed: 20, fanSpeed: 0, spoolWeight: 500, density: 1.19, dryingTemp: 50, dryingTime: '6h', notes: GENERIC_NOTE },
];
